### ISSUE TITLE
UI updates for Cross Optimization Module, misc other small changes

### ISSUE THREAD

**Issue by keocorak** [keocorak/XingAppV2#12]
In theme:

- Makes 'selected' color change consistent across the sidebar and body tabs (low priority)

In Inventory/Sorting Module:

- Change order of Male Parents and Female Parents columns

In Cross Optimization Module:
- Check to make sure Parent 1 is from the "Female.Parent" list and Parent 2 is from the "Male.Parent" List. Change column headers from "Parent 1" and "Parent 2" to "Female.Parent" and "Male.Parent", respectively. 
- Change Culling Pairwise K parameter value selector to a slider with values 0-1, set default to 1
- Change Proportion to Select parameter value selector to a slider with values 0-1, set default to 0.05
- Round reported Y and K values to 3 decimal places
- Left join the optimized crossing plan table with the table from the 'Previous Crosses' module, joining by columns 1 and 2. Freeze first two columns in table, let other columns horizontal scroll.

**Comment by romil2807** [comment]
All the modifications are made in branch "Romil"
